const sr = {
  nav: {
    services: 'Usluge',
    why: 'Zašto Boki',
    gallery: 'Galerija',
    location: 'Lokacija',
    book: 'Zakaži termin',
  },
  hero: {
    kicker: 'Vulkanizer',
    line1: 'GUME, FELNE',
    line2: 'I',
    hl: 'BALANS',
    line3: 'KAKO TREBA.',
    sub: 'Gume, felne i balans — brzo, pošteno, kako treba. Polovne i nove gume, čelične i alu felne, precizno balansiranje. Svrati ili zakaži termin online.',
    ctaBook: 'Zakaži termin',
    openToday: 'Otvoreno danas',
    tag: 'Montaža · Balans · Felne',
    stat1label: 'Google recenzija',
    stat2label: 'sve dimenzije guma',
    stat3value: 'Brzo',
    stat3label: 'bez čekanja danima',
  },
  services: {
    kicker: 'Šta radimo',
    title: 'Usluge',
    desc: 'Sve vezano za gume i felne na jednom mestu — od montaže do farbanja felni.',
    items: [
      { title: 'Montaža i demontaža', desc: 'Brza i pažljiva zamena guma za putnička i terenska vozila, bez oštećenja felne.' },
      { title: 'Balansiranje točkova', desc: 'Precizno balansiranje na mašini — kraj vibracijama volana na većim brzinama.' },
      { title: 'Polovne gume', desc: 'Veliki izbor proverenih polovnih guma u ekstra stanju, dimenzije 10—18 cola.' },
      { title: 'Nove gume', desc: 'Michelin, Pirelli, Kleber, Kumho, Sava — letnje, zimske i sve-sezonske.' },
      { title: 'Čelične i alu felne', desc: 'Prodaja čeličnih i aluminijumskih felni, veliki izbor dimenzija.' },
      { title: 'Ispravljanje i farbanje felni', desc: 'Restauracija oštećenih felni — ispravljanje, farbanje i vraćanje u život.' },
    ],
  },
  why: {
    kicker: 'Zašto baš mi',
    heading: 'Posao se zna.',
    hl: 'Bez priče.',
    lead: 'Kod nas dolaziš kad treba da se uradi kako treba — brzo, korektno i bez naknadnih iznenađenja na računu.',
    points: [
      'Iskusan majstor — radimo godinama u Kaluđerici',
      'Poštene cene, kažemo unapred koliko je',
      'Polovne i nove gume svih dimenzija na stanju',
      'Brza usluga — ne čeka se danima na termin',
      'Felne: prodaja, ispravljanje i farbanje',
    ],
    cta: 'Zakaži termin',
    reviewsLabel: 'zadovoljnih mušterija',
  },
  booking: {
    kicker: 'Brzo i bez gužve',
    heading: 'Zakaži',
    hl: 'termin',
    desc: 'Popuni par polja, klikni — i otvara ti se gotova poruka za WhatsApp. Samo je pošalji, javljamo se sa potvrdom termina. Nema komplikovanih formulara.',
    preferCall: 'Više voliš poziv?',
    labels: {
      name: 'Ime',
      phone: 'Telefon',
      service: 'Usluga',
      vehicle: 'Vozilo (opciono)',
      tireSize: 'Dimenzija gume (opciono)',
      when: 'Kad ti odgovara',
      note: 'Napomena (opciono)',
    },
    placeholders: {
      name: 'Tvoje ime',
      phone: '06x...',
      vehicle: 'npr. Golf 7',
      tireSize: '205/55 R16',
      when: 'npr. sutra ujutru, ovaj petak...',
      note: 'Bilo šta dodatno...',
    },
    options: ['Zamena guma', 'Balansiranje', 'Polovne gume', 'Nove gume', 'Felne (prodaja/ispravljanje/farbanje)', 'Drugo / nisam siguran'],
    cta: 'Pošalji na WhatsApp',
    note: 'Otvara WhatsApp sa popunjenom porukom — ništa se ne šalje automatski dok ti ne potvrdiš.',
    waGreeting: 'Zdravo Boki! Želeo bih da zakažem termin.',
    waLabels: { name: 'Ime', phone: 'Telefon', service: 'Usluga', vehicle: 'Vozilo', tireSize: 'Dimenzija', when: 'Termin', note: 'Napomena' },
    waDefault: 'Zdravo, zanima me termin za gume.',
  },
  location: {
    kicker: 'Gde smo',
    title: 'Lokacija',
    descPrefix: 'Nalazimo se u',
    descSuffix: '. Lako se parkira ispred — svrati kad ti odgovara.',
    address: 'Adresa',
    phone: 'Telefon',
    hours: 'Radno vreme',
    navBtn: 'Otvori navigaciju',
    mapTitle: 'Mapa — Vulkanizer Boki',
    closed: 'Zatvoreno',
  },
  shopHours: [
    { day: 'Ponedeljak — Petak', time: '08:00 — 16:00', closed: false },
    { day: 'Subota', time: '08:00 — 14:00', closed: false },
    { day: 'Nedelja', time: 'Zatvoreno', closed: true },
  ],
  gallery: {
    kicker: 'Iz radionice',
    title: 'Galerija',
    desc: 'Gume, felne i posao u toku — par fotografija iz naše svakodnevice.',
    photos: ['Auto u radionici', 'Felna i guma izbliza', 'Alu felna detalj', 'Servisni alat', 'Naslagane gume', 'Detalj točka i kočnice'],
  },
  footer: {
    servicesTitle: 'Usluge',
    linksTitle: 'Brze veze',
    contactTitle: 'Kontakt',
    services: ['Zamena guma', 'Balansiranje', 'Polovne i nove gume', 'Felne'],
    links: ['Galerija', 'Lokacija', 'Zakaži termin', 'Navigacija'],
    rights: 'Sva prava zadržana.',
    tagline: 'Gume · Felne · Balans',
    reviewsLabel: 'recenzija',
    shopTagline: 'Gume, felne i balans — brzo, pošteno, kako treba.',
  },
  mobileNav: {
    contact: 'Kontakt',
    location: 'Lokacija',
    book: 'Zakaži',
    ask: 'Pitaj',
  },
  chat: {
    agentName: 'Boki — pomoćnik',
    agentStatus: 'Obično odgovara odmah',
    greeting: 'Zdravo! 👋 Ja sam Bokijev pomoćnik. Pitaj me o gumama, felnama, ceni ili kako da zakažeš — tu sam.',
    waBtn: 'Piši na WhatsApp',
    callBtn: 'Pozovi',
    waDefault: 'Zdravo, zanima me termin za gume.',
    knowledge: [
      { q: 'Koje usluge radite?', a: 'Radimo montažu, demontažu i <b>balansiranje guma</b>, prodaju polovnih i novih guma (Michelin, Pirelli, Kleber, Kumho, Sava), čelične i alu felne, kao i <b>ispravljanje i farbanje felni</b>. Sve na jednom mestu.' },
      { q: 'Koliko košta zamena guma?', a: 'Cena zavisi od dimenzije i tipa gume. Najbrže je da nam javiš dimenziju (npr. 205/55 R16) na WhatsApp ili pozivom — odmah dobiješ tačnu cenu. 👍' },
      { q: 'Da li imate polovne gume?', a: 'Da! Imamo veliki izbor <b>polovnih guma u ekstra stanju</b>, dimenzije od 10 do 18 cola. Javi koja ti dimenzija treba pa proverimo na stanju.' },
      { q: 'Gde se nalazite?', a: 'Nalazimo se u <b>{{addr}}, {{city}}</b>. Lako se parkira ispred. Klikni na "Lokacija" dole pa otvori navigaciju do nas. 📍' },
      { q: 'Radno vreme?', a: 'Radimo <b>radnim danima 08–16h</b>, subotom 08–14h. Nedeljom ne radimo. Za hitne stvari najbolje pozovi unapred.' },
      { q: 'Kako da zakažem termin?', a: 'Super lako — skroluj do sekcije <b>"Zakaži termin"</b> ili klikni dugme dole. Popuniš par polja i otvara ti se poruka za WhatsApp, pa samo pošalješ. ⚡' },
      { q: 'Radite li balansiranje?', a: 'Naravno. Balansiranje točkova radimo na preciznoj mašini — gura li ti volan na brzini, to obično rešava balans. Svrati ili zakaži termin.' },
    ],
  },
}

const en = {
  nav: {
    services: 'Services',
    why: 'Why Boki',
    gallery: 'Gallery',
    location: 'Location',
    book: 'Book Appointment',
  },
  hero: {
    kicker: 'Tire Shop',
    line1: 'TIRES, RIMS',
    line2: '&',
    hl: 'BALANCING',
    line3: 'DONE RIGHT.',
    sub: 'Used and new tires, steel and alloy rims, precision balancing. Drop by or book your appointment online.',
    ctaBook: 'Book Appointment',
    openToday: 'Open today',
    tag: 'Mounting · Balancing · Rims',
    stat1label: 'Google reviews',
    stat2label: 'all tire sizes',
    stat3value: 'Fast',
    stat3label: 'no long wait',
  },
  services: {
    kicker: 'What we do',
    title: 'Services',
    desc: 'Everything related to tires and rims in one place — from mounting to rim painting.',
    items: [
      { title: 'Mounting & Dismounting', desc: 'Fast and careful tire change for passenger and off-road vehicles, without damaging the rim.' },
      { title: 'Wheel Balancing', desc: 'Precision machine balancing — eliminates steering wheel vibrations at higher speeds.' },
      { title: 'Used Tires', desc: 'Large selection of quality used tires in excellent condition, sizes 10—18 inches.' },
      { title: 'New Tires', desc: 'Michelin, Pirelli, Kleber, Kumho, Sava — summer, winter and all-season.' },
      { title: 'Steel & Alloy Rims', desc: 'Sale of steel and aluminum rims, large selection of sizes.' },
      { title: 'Rim Straightening & Painting', desc: 'Restoration of damaged rims — straightening, painting and bringing them back to life.' },
    ],
  },
  why: {
    kicker: 'Why choose us',
    heading: 'The work speaks',
    hl: 'for itself.',
    lead: 'Come to us when you need it done right — fast, honest and without any surprise charges.',
    points: [
      'Experienced mechanic — serving Kaluđerica for years',
      'Fair prices, we tell you upfront what it costs',
      'Used and new tires of all sizes in stock',
      'Fast service — no waiting days for an appointment',
      'Rims: sales, straightening and painting',
    ],
    cta: 'Book Appointment',
    reviewsLabel: 'satisfied customers',
  },
  booking: {
    kicker: 'Quick and hassle-free',
    heading: 'Book an',
    hl: 'appointment',
    desc: "Fill in a few fields, click — and a ready-made WhatsApp message opens. Just send it and we'll confirm your slot. No complicated forms.",
    preferCall: 'Prefer a call?',
    labels: {
      name: 'Name',
      phone: 'Phone',
      service: 'Service',
      vehicle: 'Vehicle (optional)',
      tireSize: 'Tire size (optional)',
      when: 'When works for you',
      note: 'Note (optional)',
    },
    placeholders: {
      name: 'Your name',
      phone: '+381...',
      vehicle: 'e.g. Golf 7',
      tireSize: '205/55 R16',
      when: 'e.g. tomorrow morning, this Friday...',
      note: 'Anything else...',
    },
    options: ['Tire Change', 'Balancing', 'Used Tires', 'New Tires', 'Rims (sale/straightening/painting)', 'Other / not sure'],
    cta: 'Send via WhatsApp',
    note: 'Opens WhatsApp with a pre-filled message — nothing is sent automatically until you confirm.',
    waGreeting: "Hello Boki! I'd like to book an appointment.",
    waLabels: { name: 'Name', phone: 'Phone', service: 'Service', vehicle: 'Vehicle', tireSize: 'Tire size', when: 'Appointment', note: 'Note' },
    waDefault: "Hello, I'd like to inquire about an appointment.",
  },
  location: {
    kicker: 'Find us',
    title: 'Location',
    descPrefix: "We're located in",
    descSuffix: '. Easy parking out front — drop by whenever it suits you.',
    address: 'Address',
    phone: 'Phone',
    hours: 'Working Hours',
    navBtn: 'Open Navigation',
    mapTitle: 'Map — Vulkanizer Boki',
    closed: 'Closed',
  },
  shopHours: [
    { day: 'Monday — Friday', time: '08:00 — 16:00', closed: false },
    { day: 'Saturday', time: '08:00 — 14:00', closed: false },
    { day: 'Sunday', time: 'Closed', closed: true },
  ],
  gallery: {
    kicker: 'From the workshop',
    title: 'Gallery',
    desc: 'Tires, rims and work in progress — a few photos from our daily routine.',
    photos: ['Car in the workshop', 'Rim and tire close-up', 'Alloy rim detail', 'Service tools', 'Stacked tires', 'Wheel and brake detail'],
  },
  footer: {
    servicesTitle: 'Services',
    linksTitle: 'Quick Links',
    contactTitle: 'Contact',
    services: ['Tire Change', 'Balancing', 'Used & New Tires', 'Rims'],
    links: ['Gallery', 'Location', 'Book Appointment', 'Navigation'],
    rights: 'All rights reserved.',
    tagline: 'Tires · Rims · Balancing',
    reviewsLabel: 'reviews',
    shopTagline: 'Tires, rims and balancing — fast, fair, done right.',
  },
  mobileNav: {
    contact: 'Contact',
    location: 'Location',
    book: 'Book',
    ask: 'Ask',
  },
  chat: {
    agentName: 'Boki — Assistant',
    agentStatus: 'Usually responds immediately',
    greeting: "Hello! 👋 I'm Boki's assistant. Ask me about tires, rims, prices or how to book — I'm here to help.",
    waBtn: 'Write on WhatsApp',
    callBtn: 'Call',
    waDefault: "Hello, I'd like to inquire about an appointment.",
    knowledge: [
      { q: 'What services do you offer?', a: 'We do <b>tire mounting, dismounting and balancing</b>, sell used and new tires (Michelin, Pirelli, Kleber, Kumho, Sava), steel and alloy rims, and offer <b>rim straightening and painting</b>. Everything in one place.' },
      { q: 'How much does a tire change cost?', a: 'The price depends on the tire size and type. The fastest way is to send us the size (e.g. 205/55 R16) via WhatsApp or phone — you\'ll get an exact price right away. 👍' },
      { q: 'Do you have used tires?', a: 'Yes! We have a large selection of <b>quality used tires in excellent condition</b>, sizes 10 to 18 inches. Let us know what size you need and we\'ll check availability.' },
      { q: 'Where are you located?', a: 'We\'re located at <b>{{addr}}, {{city}}</b>. Easy parking out front. Click "Location" below to open navigation. 📍' },
      { q: 'Working hours?', a: 'We\'re open <b>Monday–Friday 08–16h</b>, Saturday 08–14h. Closed on Sundays. For urgent matters, it\'s best to call ahead.' },
      { q: 'How do I book an appointment?', a: 'Super easy — scroll to the <b>"Book Appointment"</b> section or click the button below. Fill in a few fields and a WhatsApp message opens — just send it. ⚡' },
      { q: 'Do you do wheel balancing?', a: 'Of course. We do precision wheel balancing — if your steering wheel vibrates at speed, balancing usually fixes it. Drop by or book an appointment.' },
    ],
  },
}

export const useT = () => {
  const locale = useLocale()
  return computed(() => (locale.value === 'en' ? en : sr))
}
